#!/usr/bin/env bash

INSTANCE_ID="i-04a45a6eb19a05ccb"
ELASTIC_IP="34.235.250.194"
USER="ubuntu"
KEY=$HOME/.aws/advin.pem

PARAMS=""
case "$1" in
    -s|--ssh)
        ssh -i ${KEY} ${USER}@${ELASTIC_IP}
        ;;
    --stop)
        currentTime=$(date)
        echo $currentTime   ${INSTANCE_ID} >> $HOME/AWS/.bbstatusLog
        docker run --rm -it -v ~/.aws:/root/.aws \
            -v $(pwd):/aws amazon/aws-cli:latest \
            ec2 stop-instances \
            --instance-ids ${INSTANCE_ID} --force \
            --query StoppingInstances[0].CurrentState.Name >> $HOME/AWS/.bbstatusLog
        cat $HOME/AWS/.bbstatusLog  | tail -3
        ;;
    --start)
        currentTime=$(date)
        echo $currentTime   ${INSTANCE_ID} >> $HOME/AWS/.bbstatusLog
       docker run --rm -it -v ~/.aws:/root/.aws \
            -v $(pwd):/aws amazon/aws-cli:latest \
            ec2 start-instances --instance-ids ${INSTANCE_ID} \
            --query StartingInstances[0].CurrentState.Name >> $HOME/AWS/.bbstatusLog
        currentTime=$(date)
        cat $HOME/AWS/.bbstatusLog  | tail -3
        ;;
    --copy)
        scp -i ${KEY} -r $2 ${USER}@${ELASTIC_IP}:$3
        ;;
    --paste)
        scp -i ${KEY} -r ${USER}@${ELASTIC_IP}:$2 $3
        ;;
    --status)
        currentTime=$(date)
        echo $currentTime   ${INSTANCE_ID} >> $HOME/AWS/.bbstatusLog
        docker run --rm -it -v ~/.aws:/root/.aws \
            -v $(pwd):/aws amazon/aws-cli:latest \
            ec2 describe-instance-status \
            --instance-id ${INSTANCE_ID}  \
            --query StartingInstances[0].CurrentState.Name >> $HOME/AWS/.bbstatusLog
        cat $HOME/AWS/.bbstatusLog  | tail -3
        ;;
    --sync)
        rsync -r --delete --progress -e "ssh -i $HOME/AWS/TrainBrain.pem" \
            $HOME/github/tl-toolkit ${USER}@${ELASTIC_IP}:/home/ubuntu/
        currentTime=$(date)
        echo $currentTime   ${INSTANCE_ID} >> $HOME/AWS/.bbstatusLog
        echo "syncing" >> .statusLog
        cat $HOME/AWS/.bbstatusLog  | tail -3
        ;;
    -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        ;;
    *) # preserve positional arguments
        PARAMS="$PARAMS $1"
        ;;
esac

# set positional arguments in their proper place
eval set -- "$PARAMS"
